name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java and Scala
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'
    
    - name: Check code formatting
      run: sbt scalafmtCheckAll
    
    - name: Compile
      run: sbt compile
    
    - name: Run tests
      run: sbt test
