name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java and Scala
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'
    
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    
    - name: Create minimal .env file for CI
      run: |
        echo "POSTGRES_HOST=localhost" > .env
        echo "POSTGRES_PORT=5432" >> .env
        echo "POSTGRES_DB=testdb" >> .env
        echo "POSTGRES_USER=testuser" >> .env
        echo "POSTGRES_PASSWORD=testpass" >> .env
    
    - name: Check code formatting
      run: sbt scalafmtCheckAll
    
    - name: Compile
      run: sbt compile
    
    - name: Run tests
      run: sbt test

    - name: Run tests with coverage
      run: sbt coverage test coverageReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./target/scala-*/scoverage-report/scoverage.xml
        fail_ci_if_error: false
